In [1]:
import tensorflow as tf

In [2]:
X = tf.placeholder(tf.float32, [None, 3]) # None은 크기가 아직 정해지지 않았다는 것
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [3]:
x_data = [[1,2,3], [4, 5, 6]]

In [5]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [6]:
expr = tf.matmul(X, W) + b

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-1.1733692   0.25604853]
 [-1.2651159   0.7616679 ]
 [ 0.40414995 -0.7242929 ]]
=== b ===
[[-0.19392513]
 [-0.05816038]]
=== expr ===
[[-2.6850762 -0.5874195]
 [-8.652317   0.428616 ]]
